namespace KeyboardInterceptor;

public static class SmartKeyboardTranslate
{
    public static string ToKey(int keyCode)
    {
        String key = "";

        if (keyCode == 8) key = "[Back]";
        else if (keyCode == 9) key = "[TAB]";
        else if (keyCode == 13) key = "[Enter]";
        else if (keyCode == 19) key = "[Pause]";
        else if (keyCode == 20) key = "[Caps Lock]";
        else if (keyCode == 27) key = "[Esc]";
        else if (keyCode == 32) key = "[Space]";
        else if (keyCode == 33) key = "[Page Up]";
        else if (keyCode == 34) key = "[Page Down]";
        else if (keyCode == 35) key = "[End]";
        else if (keyCode == 36) key = "[Home]";
        else if (keyCode == 37) key = "[Left]";
        else if (keyCode == 38) key = "[Up]";
        else if (keyCode == 39) key = "[Right]";
        else if (keyCode == 40) key = "[Down]";
        else if (keyCode == 44) key = "[Print Screen]";
        else if (keyCode == 45) key = "[Insert]";
        else if (keyCode == 46) key = "[Delete]";
        else if (keyCode == 48) key = "0";
        else if (keyCode == 49) key = "1";
        else if (keyCode == 50) key = "2";
        else if (keyCode == 51) key = "3";
        else if (keyCode == 52) key = "4";
        else if (keyCode == 53) key = "5";
        else if (keyCode == 54) key = "6";
        else if (keyCode == 55) key = "7";
        else if (keyCode == 56) key = "8";
        else if (keyCode == 57) key = "9";
        else if (keyCode == 65) key = "a";
        else if (keyCode == 66) key = "b";
        else if (keyCode == 67) key = "c";
        else if (keyCode == 68) key = "d";
        else if (keyCode == 69) key = "e";
        else if (keyCode == 70) key = "f";
        else if (keyCode == 71) key = "g";
        else if (keyCode == 72) key = "h";
        else if (keyCode == 73) key = "i";
        else if (keyCode == 74) key = "j";
        else if (keyCode == 75) key = "k";
        else if (keyCode == 76) key = "l";
        else if (keyCode == 77) key = "m";
        else if (keyCode == 78) key = "n";
        else if (keyCode == 79) key = "o";
        else if (keyCode == 80) key = "p";
        else if (keyCode == 81) key = "q";
        else if (keyCode == 82) key = "r";
        else if (keyCode == 83) key = "s";
        else if (keyCode == 84) key = "t";
        else if (keyCode == 85) key = "u";
        else if (keyCode == 86) key = "v";
        else if (keyCode == 87) key = "w";
        else if (keyCode == 88) key = "x";
        else if (keyCode == 89) key = "y";
        else if (keyCode == 90) key = "z";
        else if (keyCode == 91) key = "[Windows]";
        else if (keyCode == 92) key = "[Windows]";
        else if (keyCode == 93) key = "[List]";
        else if (keyCode == 96) key = "0";
        else if (keyCode == 97) key = "1";
        else if (keyCode == 98) key = "2";
        else if (keyCode == 99) key = "3";
        else if (keyCode == 100) key = "4";
        else if (keyCode == 101) key = "5";
        else if (keyCode == 102) key = "6";
        else if (keyCode == 103) key = "7";
        else if (keyCode == 104) key = "8";
        else if (keyCode == 105) key = "9";
        else if (keyCode == 106) key = "*";
        else if (keyCode == 107) key = "+";
        else if (keyCode == 109) key = "-";
        else if (keyCode == 110) key = ",";
        else if (keyCode == 111) key = "/";
        else if (keyCode == 112) key = "[F1]";
        else if (keyCode == 113) key = "[F2]";
        else if (keyCode == 114) key = "[F3]";
        else if (keyCode == 115) key = "[F4]";
        else if (keyCode == 116) key = "[F5]";
        else if (keyCode == 117) key = "[F6]";
        else if (keyCode == 118) key = "[F7]";
        else if (keyCode == 119) key = "[F8]";
        else if (keyCode == 120) key = "[F9]";
        else if (keyCode == 121) key = "[F10]";
        else if (keyCode == 122) key = "[F11]";
        else if (keyCode == 123) key = "[F12]";
        else if (keyCode == 144) key = "[Num Lock]";
        else if (keyCode == 145) key = "[Scroll Lock]";
        else if (keyCode == 160) key = "[Shift]";
        else if (keyCode == 161) key = "[Shift]";
        else if (keyCode == 162) key = "[Ctrl]";
        else if (keyCode == 163) key = "[Ctrl]";
        else if (keyCode == 164) key = "[Alt]";
        else if (keyCode == 165) key = "[Alt]";
        else if (keyCode == 187) key = "=";
        else if (keyCode == 186) key = "ç";
        else if (keyCode == 188) key = ",";
        else if (keyCode == 189) key = "-";
        else if (keyCode == 190) key = ".";
        else if (keyCode == 192) key = "'";
        else if (keyCode == 191) key = ";";
        else if (keyCode == 193) key = "/";
        else if (keyCode == 194) key = ".";
        else if (keyCode == 219) key = "´";
        else if (keyCode == 220) key = "]";
        else if (keyCode == 221) key = "[";
        else if (keyCode == 222) key = "~";
        else if (keyCode == 226) key = "\\";
        else key = "[" + keyCode + "]";

        return key;
    }
}